# Generated by Django 3.2 on 2022-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0002_alter_roomtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
