# Generated by Django 3.2 on 2022-05-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Reviews'},
        ),
    ]
